### ISSUE TITLE
adding a package included in manage.py

### ISSUE THREAD

**Issue by boazin** [getweber/weber-backend#16]
I added a package (`apscheduler`) I'm importing in manage.py
added it to `app.txt` under deps,

Still running `make testserver` gets me:
`ImportError: No module named apscheduler.scheduler`

There are other packages used in manage.py, and I know when running `make testserver` on the first time, pip is running and installing. Why isn't it happening on the second time? Any bootstrap code I'm missing?

**Comment by vmalloc** [comment]
Once you add it to your app.txt, you should run `make testserver` again -- if it was running before it won't pick up on the change you made... Is that what you experienced?

**Comment by boazin** [comment]
nope. no server is alive...
in `manage.py` I have:
`from apscheduler.scheduler import Scheduler`

running:
`make testserver`
getting:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from apscheduler.scheduler import Scheduler
ImportError: No module named apscheduler.scheduler
```

**Comment by vmalloc** [comment]
You can't write it at the module level. It has to be inside a function decorated with the `requires_env` decorator...

**Comment by boazin** [comment]
got it. Thanks
