### ISSUE TITLE
vagrant can't install postgresql out of the box

### ISSUE THREAD

**Issue by boazin** [getweber/weber-backend#17]
Since the vagrant is using Ubuntu trusty, installing postgresql includes some extra steps (editing the `/etc/apt/sources.list.d/pgdg.list` `wget` etc.) described in http://www.postgresql.org/download/linux/ubuntu/

It would have been nice to get the weber to work out of the box. 

Newer Ubuntu? patching ansible to do it?

**Comment by boazin** [comment]
managed to pass this one, will make a PR tomorrow

**Comment by vmalloc** [comment]
We officially support Ubuntu 15.04 and above, not earlier, since we require systemd...

We have passing tests that run nightly to make sure it works, so I'm guessing this is a problem with older Ubuntus, which will cause issues regardless. Let me know if you find otherwise...

**Comment by vmalloc** [comment]
Just double checked - it's not using trusty. The default config says:

```
config.vm.define :ubuntu do |config|
    config.vm.box = "chef/ubuntu-15.04"
    config.vm.host_name = "ubuntu"
    config.vm.forward_port 80, 8002
  end
```

**Comment by boazin** [comment]
I made a manual merge. Must have missed it.

Which elements depend on systemd?

**Comment by vmalloc** [comment]
Mostly the fact that we dropped supervisord and now use it for service management, and thus we get support for CentOS and Arch. It's a much saner deployment environment and doesn't suffer from the quirks of supervisor.
