### ISSUE TITLE
unrecoverable error if vagrant fails

### ISSUE THREAD

**Issue by boazin** [getweber/weber-backend#18]
If a `python manage.py deploy --dest vagrant` fails, subsequent calls will not succeed

The error:

```
The box 'chef/centos-7.0' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/chef/centos-7.0"]
Error: The requested URL returned error: 404 Not Found
```

Only `vagrant destroy` solves the problem

**Comment by vmalloc** [comment]
@r-darwish ?

**Comment by boazin** [comment]
In the meantime I found out that the chef/XXX boxes don't exist. 
I think it should be `ubuntu/vivid64` for ubuntu and `bento/centos-7.1` for centOS

**Comment by r-darwish** [comment]
I updated the names of the boxes so it should work now. Thanks for reporting.
