### ISSUE TITLE
nginx.conf not updated in ubuntu - bug or feature?

### ISSUE THREAD

**Issue by boazin** [getweber/weber-backend#19]
Hey Guys,
Quick question about an old nginx change:

https://github.com/getweber/weber-backend/commit/99cc96646acd4b02f9f10023df1b1cd578498772

Do we don't touch nginx.conf in case of ubuntu on purpose? or is it a bug?

**Comment by vmalloc** [comment]
This is intentional. Ubuntu and Debian have a proper nginx config which defers to loading from `conf.d` or `sites-enabled`. Arch and CentOS do not.

**Comment by boazin** [comment]
OK. So if I want to override a general config (such as `worker_rlimit_nofile`), it is still recommended to do it in the site_conf file?

**Comment by vmalloc** [comment]
well you can always add another ansible step modifying the global config using `lineinfile` etc., but it really depends on the platform you target
